version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: country
      - name: league
      - name: match
      - name: player
      - name: player_attributes
      - name: team
      - name: team_attributes